#!/bin/bash

#####################################################
# OCR PDF Action
# Created by github.com/MarketingPipeline
#####################################################
INPUTFILE=$1
OUTPUTFILE=$2



### File Path Option
if [ -z "$INPUTFILE" ]
then
      echo "\Input file was not provided or could not be found, please provide a valid input file location - closing the script."
      exit 3 
else
      echo "\Input file was provided!"
fi


### Overwrite files

if [ -z "$OUTPUTFILE"]
then
      echo "\Output file was not provided or could not be found, please provide a valid output file location - closing the script."
      exit 3 
else
      echo "\Output file was provided, starting script"
fi


ocrmypdf $INPUTFILE $OUTPUTFILE
